name: Build

on: [push, pull_request]

jobs:
  windows:

    runs-on: windows-latest
    env:
      workdir: "${{ github.workspace }}/build"
      configuration: Release
    strategy:
      matrix:
        arch: [x64, Win32]

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S "${{ github.workspace }}" -B "${{ env.workdir }}" -DCPACK_GENERATOR="7Z;ZIP" -A ${{ matrix.arch }} -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W4" -DBUILD_SHARED_LIBS=TRUE
    - name: Build
      run: cmake --build "${{ env.workdir }}" --config ${{ env.configuration }} -j 4
    - name: Test
      run: |
        cd "${{ env.workdir }}"
        ctest -C ${{ env.configuration }}
    - name: Package
      run: cmake --build "${{ env.workdir }}" --config ${{ env.configuration }} --target package
    - name: Installer
      run: cmake --build "${{ env.workdir }}" --config ${{ env.configuration }} --target create-installer
    - name: Upload-Installer
      uses: actions/upload-artifact@v2.0.1
      with:
        path: "${{ env.workdir }}/Output/*.exe"
    - name: Upload-ZIPArchives
      uses: actions/upload-artifact@v2.0.1
      with:
        path: "${{ env.workdir }}/*.zip"
    - name: Upload-7ZArchives
      uses: actions/upload-artifact@v2.0.1
      with:
        path: "${{ env.workdir }}/*.7z"
